// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI commands (migrate, db pull, db push) need a non-pgbouncer connection;
    // the transaction-mode pooler (DATABASE_URL, port 6543) closes the connection
    // mid-introspection. The generated client at runtime still uses DATABASE_URL
    // via schema.prisma's `url` field.
    url: process.env["DIRECT_URL"],
  },
});
