const mongoose = require('mongoose');

const StagingSchema = new mongoose.Schema({
  jobId: {
    type: String, // ID generated by BullMQ for the import job
    required: true,
    index: true
  },
  entityType: {
    type: String,
    required: true,
    enum: ['Vendor', 'Material', 'BOM']
  },
  rowNumber: {
    type: Number,
    required: true
  },
  rawData: {
    type: mongoose.Schema.Types.Mixed, // The exact parsed JSON from Excel/CSV
    required: true
  },
  parsedData: {
    type: mongoose.Schema.Types.Mixed, // The cast/formatted data ready for insertion
    default: null
  },
  validationErrors: [{
    field: String,
    message: String
  }],
  status: {
    type: String,
    enum: ['pending', 'committed', 'failed'],
    default: 'pending',
    index: true
  },
  commitError: {
    type: String, // Holds MongoDB error string if commit phase fails for this row
    default: null
  },
  createdAt: {
    type: Date,
    default: Date.now
  }
});

module.exports = mongoose.model('Staging', StagingSchema);
